### ISSUE TITLE
Excluding shell history files and python local packages

### ISSUE THREAD

**Issue by jackm** [rubo77/rsync-homedir-excludes#24]
What is the reason behind excluding files such as `.bash_history`, `.zsh_history`, and `.python_history`?
Also, why exclude `.local/lib/python*`, which contains locally installed Python packages to the user scheme? A user might want to keep the Python packages that they've already installed into their home directory in their backup.
I would have thought that backing up files/folders such as these would be somewhat important. I'm more curious as to why they were excluded to begin with.

**Comment by rubo77** [comment]
you are right, no idea why they were excluded by default
