### ISSUE TITLE
Electron Apps clearup

### ISSUE THREAD

**Issue by bell07** [rubo77/rsync-homedir-excludes#47]
The file contains the "universal" settings for Electron Apps

```
# Electron Apps
.config/**/blob_storage
.config/**/Application Cache
.config/**/Cache
.config/**/CachedData
.config/**/Code Cache
.config/**/GPUCache

```

Some of apps are configured separately. Maybe the file should be cleared up. I am about removal of some redundant google chrome, chromium and brave lines ..

**Comment by rubo77** [comment]
I am open for a pr

**Comment by bell07** [comment]
Did looked in detail, there is no redundancy. My mistake
